---
- name: install nginx
  hosts: prod
  become: yes
  
  tasks:
  - name: Ensure nginx package is present
    apt:
      name: nginx
      state: present
  - name: Replace string
    lineinfile:
      path: /var/www/html/index.nginx-debian.html
      regexp: 'Welcom to nginx!'
      line: '<p><script> document.write (new Date().toLocaleDateString()); </script></p>'
  - name: Ensure nginx.service  is present
    service:
      name: nginx
      state: restarted